version: 0.2

phases:
  install:
    commands:
      - echo Installing angular CLI...
      - npm install -g @angular/cli
    pre_build:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist'
  