version: 0.2

phases:
  install:
    commands:
      - echo Installing angular CLI...
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - aws s3 cp dist s3://m0j0nz0r/ --recursive
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist'
  